language: python
install:
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -y python-all-dev libmad0-dev python-setuptools
script:
 - python setup.py build
 - python -m compileall -f .
